name: Python CI

on: 
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    # Step 1: Setup repo
    steps:
      - name: Check out code 
        uses: actions/checkout@v2

    #Step 2: Set up python env
      - name: Set up python 
        uses: actions/setup-python@v2
    
    # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
    # Step 4: Run tests
      - name: Run tests
        run: pytest
    
